<?php
// +----------------------------------------------------------------------
// | 浩森PHP框架 [ IeasynetPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2017~2018 北京浩森宇特互联科技有限公司 [ http://www.ieasynet.com ]
// +----------------------------------------------------------------------
// | 官方网站：http://ieasynet.com
// +----------------------------------------------------------------------
// | 开源协议 ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | 作者: 拼搏 <378184@qq.com>
// +----------------------------------------------------------------------
/**
 * 菜单信息
 */
return [
  [
    'title' => '代理平台',
    'icon' => 'fa fa-fw fa-newspaper-o',
    'url_type' => 'module',
    'url_value' => 'agent/index/index',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 100,
    'status' => 1,
    'child' => [
      [
        'title' => '通知公告',
        'icon' => 'fa fa-fw fa-folder-open-o',
        'url_type' => 'module',
        'url_value' => 'agent/index/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 1,
        'status' => 1,
        'child' => [
          [
            'title' => '查看',
            'icon' => 'fa fa-fw fa-tachometer',
            'url_type' => 'module',
            'url_value' => 'agent/index/show',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 1,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '小说列表',
        'icon' => 'fa fa-fw fa-folder-open-o',
        'url_type' => 'module',
        'url_value' => 'agent/novel/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 2,
        'status' => 1,
        'child' => [
          [
            'title' => '显示章节列表',
            'icon' => 'fa fa-fw fa-tachometer',
            'url_type' => 'module',
            'url_value' => 'agent/novel/zjlist',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 1,
            'status' => 1,
          ],
          [
            'title' => '显示小说内容',
            'icon' => 'fa fa-fw fa-tachometer',
            'url_type' => 'module',
            'url_value' => 'agent/novel/view',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 2,
            'status' => 1,
          ],
          [
            'title' => '生成推广文案',
            'icon' => 'fa fa-fw fa-tachometer',
            'url_type' => 'module',
            'url_value' => 'agent/agent/wxcreate',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 3,
            'status' => 1,
            'child' => [
              [
                'title' => '获取文章内容',
                'icon' => '',
                'url_type' => 'module',
                'url_value' => 'agent/agent/getcontent',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 1,
                'status' => 1,
              ],
              [
                'title' => '获取图片',
                'icon' => '',
                'url_type' => 'module',
                'url_value' => 'agent/agent/getimage',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 2,
                'status' => 1,
              ],
              [
                'title' => '获取模板',
                'icon' => '',
                'url_type' => 'module',
                'url_value' => 'agent/agent/gettemp',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 3,
                'status' => 1,
              ],
              [
                'title' => '获取标题',
                'icon' => '',
                'url_type' => 'module',
                'url_value' => 'agent/agent/gettitle',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 4,
                'status' => 1,
              ],
              [
                'title' => '获取底部模板',
                'icon' => '',
                'url_type' => 'module',
                'url_value' => 'agent/agent/getfooter',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 5,
                'status' => 1,
              ],
              [
                'title' => '获取章节内容',
                'icon' => '',
                'url_type' => 'module',
                'url_value' => 'agent/agent/getactirle',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 6,
                'status' => 1,
              ],
              [
                'title' => '保存文案',
                'icon' => '',
                'url_type' => 'module',
                'url_value' => 'agent/agent/savewa',
                'url_target' => '_self',
                'online_hide' => 1,
                'sort' => 7,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '生成推广链接',
            'icon' => 'fa fa-fw fa-tachometer',
            'url_type' => 'module',
            'url_value' => 'agent/agent/linkcreate',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 4,
            'status' => 1,
          ],
          [
            'title' => '查看小说内容',
            'icon' => 'fa fa-fw fa-eject',
            'url_type' => 'module',
            'url_value' => 'agent/novel/show',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 5,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '推广链接',
        'icon' => 'fa fa-fw fa-folder-open-o',
        'url_type' => 'module',
        'url_value' => 'agent/agent/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 3,
        'status' => 1,
        'child' => [
          [
            'title' => '订单明细',
            'icon' => 'fa fa-fw fa-tachometer',
            'url_type' => 'module',
            'url_value' => 'agent/agent/order',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 1,
            'status' => 1,
          ],
          [
            'title' => '文案',
            'icon' => 'fa fa-fw fa-tachometer',
            'url_type' => 'module',
            'url_value' => 'agent/agent/wxedit',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 2,
            'status' => 1,
          ],
          [
            'title' => '修改',
            'icon' => 'fa fa-fw fa-tachometer',
            'url_type' => 'module',
            'url_value' => 'agent/agent/edit',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 3,
            'status' => 1,
          ],
          [
            'title' => '删除',
            'icon' => 'fa fa-fw fa-tachometer',
            'url_type' => 'module',
            'url_value' => 'agent/agent/delete',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 4,
            'status' => 1,
          ],
          [
            'title' => '添加首页链接',
            'icon' => '',
            'url_type' => 'module',
            'url_value' => 'agent/agent/addindex',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 5,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '数据统计',
        'icon' => 'fa fa-fw fa-folder-open-o',
        'url_type' => 'module',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 4,
        'status' => 1,
        'child' => [
          [
            'title' => '订单统计',
            'icon' => 'fa fa-fw fa-tachometer',
            'url_type' => 'module',
            'url_value' => 'agent/statistical/paylog',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 1,
            'status' => 1,
          ],
          [
            'title' => '用户统计',
            'icon' => 'fa fa-fw fa-plus',
            'url_type' => 'module',
            'url_value' => 'agent/statistical/userlog',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '结算单',
        'icon' => 'fa fa-fw fa-folder-open-o',
        'url_type' => 'module',
        'url_value' => 'agent/settlement/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 5,
        'status' => 1,
        'child' => [
          [
            'title' => '提现',
            'icon' => '',
            'url_type' => 'module',
            'url_value' => 'agent/settlement/add',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 1,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '收款信息',
        'icon' => 'fa fa-fw fa-folder-open-o',
        'url_type' => 'module',
        'url_value' => 'agent/my/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 6,
        'status' => 1,
      ],
      [
        'title' => '代理商管理',
        'icon' => 'fa fa-fw fa-group',
        'url_type' => 'module',
        'url_value' => 'agent/user/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 7,
        'status' => 1,
        'child' => [
          [
            'title' => '添加代理商',
            'icon' => '',
            'url_type' => 'module',
            'url_value' => 'agent/user/add',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 1,
            'status' => 1,
          ],
          [
            'title' => '修改代理商',
            'icon' => '',
            'url_type' => 'module',
            'url_value' => 'agent/user/edit',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 2,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '提现审核',
        'icon' => 'fa fa-fw fa-money',
        'url_type' => 'module',
        'url_value' => 'agent/settlement/shenhe',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 8,
        'status' => 1,
        'child' => [
          [
            'title' => '审核成功',
            'icon' => '',
            'url_type' => 'module',
            'url_value' => 'agent/settlement/shenheadd',
            'url_target' => '_self',
            'online_hide' => 1,
            'sort' => 1,
            'status' => 1,
          ],
        ],
      ],
      [
        'title' => '全局配置',
        'icon' => 'fa fa-fw fa-th',
        'url_type' => 'module',
        'url_value' => 'agent/config/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
      ],
    ],
  ],
];
