<p><strong>Overview</strong></p>
<p>Welcome to  onlineshop, your reliable online marketplace. Please review the following basic rules that govern your use of the our onlineshop (the "Agreement"). Please note that your use of the our onlineshop (the "Site") constitutes your unconditional agreement to follow and be bound by these Terms of Use. Although you may "bookmark" a particular portion of this Site and thereby bypass this Agreement, your use of this Site still binds you to these Terms of Use.our onlineshop reserves the right to update or modify these Terms of Use at any time without prior notice to you. Your use of the Site following any such change constitutes your unconditional agreement to follow and be bound by these Terms of Use as changed. For this reason, we encourage you to review these Terms of Use whenever you use this Site.</p>
<p><strong>Use of this site</strong></p>
<p>All billing and registration information provided must be truthful and accurate. Providing any untruthful or inaccurate information may constitute a breach of these Terms of Use. By confirming your purchase at the end of the checkout process, you agree to accept and pay for the item(s) requested.</p>
<p>All materials, including images, text, illustrations, designs, icons, photographs, programs, music clips or downloads, video clips and written and other materials that are part of this Site (collectively, the "Contents") are intended solely for personal, non-commercial use. You may download or copy the Contents and other downloadable materials displayed on the Site for your personal use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Contents, the Site or any related software. All software used on this Site is the property of our onlineshop. and protected by copyright laws. The Contents and software on this Site may be used only as a purchasing resource. Any other use, including the reproduction, modification, distribution, transmission, republication, display, or performance, of the Contents on this Site is strictly prohibited.</p>
<p><strong>Objectionable Material</strong></p>
<p>You understand that by using this Site or any services provided on the Site, you may encounter Content that may be deemed by some to be offensive, indecent, or objectionable, which Content may or may not be identified as such. You agree to use the Site and any service at your sole risk and that our onlineshop. shall have no liability to you for Content that may be deemed offensive, indecent, or objectionable.</p>
<p><strong>Copyrights and Trademarks</strong></p>
<p>Unless otherwise noted, all Contents are copyrights, trademarks, trade dress and/or other intellectual property owned, controlled or licensed by our onlineshop or by third parties who have licensed their materials to our onlineshop and are protected by China and international copyright laws. The compilation (meaning the collection, arrangement, and assembly) of all Contents on this site is the exclusive property of our onlineshop and is also protected by China and its international copyright laws.</p>
<p>our onlineshop and its suppliers and licensors expressly reserve all intellectual property rights in all text, programs, products, processes, technology, content and other materials which appear on this Site. Access to this Site does not confer and shall not be considered as conferring upon anyone any license under any of our onlineshop or any third party's intellectual property rights.</p>
<p>The our onlineshop names and logos and all related product and service names, design marks and slogans are the trademarks or service marks of our onlineshop No trademark or service mark license is granted in connection with the materials contained on this Site. Access to this Site does not authorize anyone to use any name, logo or mark in any manner.
? References on this Site to any names, marks, products or services of third parties or hypertext links to third party sites or information are provided solely as a convenience to you and do not in any way constitute or imply our onlineshop endorsement, sponsorship or recommendation of the third party, information, product or service. our onlineshop is not responsible for the content of any third party sites and does not make any representations regarding the content or accuracy of material on such sites. If you decide to link to any such third party web sites, you do so entirely at your own risk.</p>
<p><strong>Indemnification</strong></p>
<p>You agree to defend, indemnify and hold harmless our onlineshop from and against any and all claims, damages, costs and expenses, including attorneys' fees, arising from or related to your use of the Site.</p>
<p><strong>Termination</strong></p>
<p>These Terms of Use are effective unless and until terminated by either you or our onlineshop You may terminate this Agreement at any time, provided that you discontinue any further use of this Site. our onlineshop also may terminate this Agreement at any time and may do so immediately without notice, and accordingly deny you access to the Site, if in our onlineshop sole discretion you fail to comply with any term or provision of this Agreement. Upon any termination of the Agreement by either you or our onlineshop, you must promptly destroy all materials downloaded or otherwise obtained from this Site, as well as all copies of such materials, whether made under the Terms of Use or otherwise. our onlineshop right to any Comments shall survive any termination of this Agreement.</p>
<p><strong>Disclaimer</strong></p>
<p>This site is provided on an "as is" and "as available" basis.our onlineshop makes no representations or warranties of any kind, expressed or implied, as to the operation of the site or the information, content, materials, or products included on this site. To the full extent permissible by applicable law, our onlineshop disclaims all warranties, expressed or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose. Without limiting the foregoing, our onlineshop disclaims any and all warranties, expressed or implied, for any merchandise offered on this site. You acknowledge, by your use of the our onlineshop web site, that your use of the site is at your sole risk. This disclaimer does not apply to any product warranty offered by the manufacturer of the item. This disclaimer constitutes an essential part of this agreement.</p>
<p><strong>Limitation of Liability</strong></p>
<p>Under no circumstances and under no legal or equitable theory, whether in tort, contract, strict liability or otherwise, shall our onlineshop or any of its employees, directors, officers, agents, vendors or suppliers be liable to you or to any other person for any indirect, special, incidental or consequential losses or damages of any nature arising out of or in connection with the use of or inability to use the our onlineshop web site, including, without limitation, damages for lost profits, loss of goodwill, loss of data, work stoppage, accuracy of results, or computer failure or malfunction, even if an authorized representative of our onlineshop has been advised of or should have known of the possibility of such damages. In no event will our onlineshop be liable for any damages in excess of the fees paid by you in connection with your use of the site during the six month period preceding the date on which the claim arose.</p>
<p><strong>Order Acceptance</strong></p>
<p>Please note that there may be certain orders that we are unable to accept and must cancel. We reserve the right, at our sole discretion, to refuse or cancel any order for any reason. Some situations that may result in your order being canceled include limitations on quantities available for purchase, inaccuracies or errors in product or pricing information, or problems identified by our credit and fraud avoidance department. We may also require additional verifications or information before accepting any order. We will contact you if all or any portion of your order is canceled or if additional information is required to accept your order.</p>
<p><strong>Pricing Information</strong></p>
<p>While our onlineshop strives to provide accurate product and pricing information, pricing or typographical errors may occur. our onlineshop cannot confirm the price of an item until after you order. In the event that an item is listed at an incorrect price or with incorrect information due to an error in pricing or product information, our onlineshop shall have the right, at our sole discretion, to refuse or cancel any orders placed for that item. In the event that an item is mis-priced,our onlineshop may, at our discretion, either contact you for instructions or cancel your order and notify you of such cancellation.</p>
<p><strong>Force Majeure</strong></p>
<p>The Sellers shall not be held responsible for the delay in shipment or non-delivery of the goods due to war, earthquake, serious flood, fire and other Force majeure causes agreed by both parties. However, the Sellers shall advise the Buyers by fax/telex, immediately of such occurrence and within fourteen days thereafter, shall send by airmail to the Buyers for their acceptance a certificate issued by the competent authorities of the place where the accident occurs as evidence thereof. Under such circumstances the Sellers, however, are still under the obligation to take all necessary measures to hasten the delivery of the goods. In case the late delivery exceeds ten weeks, the Buyers shall have the right to cancel this Contract.</p>
<p><strong>Arbitration</strong></p>
<p>Where the parties fail to settle dispute within 30 days after such dispute occurs, they agree to submit such dispute to China International Economic and Trade Arbitration Commission for arbitration which shall be conducted in accordance with the Commission''''''''s arbitration rules in effect at the time of applying for arbitration. The arbitral awards are final and binding upon both parties.</p>